#!/usr/bin/env python3
from __future__ import annotations

import struct
from pathlib import Path

ROOT = Path('Manres20260220/Data')
OUT = Path('docs/vfp-data-inventory.md')


def parse_dbf(path: Path):
    raw = path.read_bytes()
    if len(raw) < 32:
        raise ValueError('too small')

    version = raw[0]
    year, month, day = raw[1], raw[2], raw[3]
    records = struct.unpack_from('<I', raw, 4)[0]
    header_len = struct.unpack_from('<H', raw, 8)[0]
    record_len = struct.unpack_from('<H', raw, 10)[0]

    fields = []
    offset = 32
    while offset + 32 <= len(raw):
        if raw[offset] == 0x0D:
            break
        desc = raw[offset:offset + 32]
        name = desc[0:11].split(b'\x00', 1)[0].decode('latin1', errors='ignore').strip()
        ftype = chr(desc[11])
        flen = desc[16]
        fdec = desc[17]
        fields.append((name, ftype, flen, fdec))
        offset += 32

    return {
        'version': version,
        'date': f"{1900 + year:04d}-{month:02d}-{day:02d}",
        'records': records,
        'header_len': header_len,
        'record_len': record_len,
        'fields': fields,
    }


def main() -> None:
    dbfs = sorted(ROOT.glob('*.DBF')) + sorted(ROOT.glob('*.dbf'))
    seen = set()
    deduped = []
    for p in dbfs:
        k = p.name.lower()
        if k in seen:
            continue
        seen.add(k)
        deduped.append(p)

    lines = []
    lines.append('# VFP Data Inventory')
    lines.append('')
    lines.append('This file is auto-generated by `scripts/extract_dbf_schema.py`.')
    lines.append('')
    lines.append(f'- Data folder: `{ROOT}`')
    lines.append(f'- Tables discovered: **{len(deduped)}**')
    lines.append('')

    for dbf in deduped:
        info = parse_dbf(dbf)
        lines.append(f"## {dbf.name}")
        lines.append('')
        lines.append(f"- Last update in header: `{info['date']}`")
        lines.append(f"- Records: **{info['records']}**")
        lines.append(f"- DBF version byte: `{info['version']}`")
        lines.append(f"- Header length: `{info['header_len']}` bytes")
        lines.append(f"- Record length: `{info['record_len']}` bytes")
        lines.append('')
        lines.append('| Field | Type | Length | Decimals |')
        lines.append('|---|---:|---:|---:|')
        for name, ftype, flen, fdec in info['fields']:
            lines.append(f"| `{name}` | `{ftype}` | {flen} | {fdec} |")
        lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
